### ISSUE TITLE
Una extensión a JSON

### ISSUE THREAD

**Issue by pricco** [mvdjs/meetups#4]
JSON es el formato de serialización de datos más usado con Javascript. En esta charla veremos algunas de sus limitaciones para manejar estructuras de datos complejas; y propondré una posible extensión para solucionarlas.

Por @LeonardoVal

**Comment by pricco** [comment]
:+1:

**Comment by Mictian** [comment]
:+1:

**Comment by marcelor** [comment]
:+1:

**Comment by mprunell** [comment]
:+1:

**Comment by ssassi** [comment]
:+1:

**Comment by juancarlosqr** [comment]
:+1:

**Comment by agucabral21** [comment]
:+1:
